version: '3.9'

services:
  django:
    build:
      context: .
    container_name: techcity-erp
    command: gunicorn techcity.wsgi:application --bind 0.0.0.0:8300
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always

  # celery:
  #   build:
  #     context: .
  #   container_name: celery_worker
  #   command: celery -A techcity worker --loglevel=info
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #   restart: always

  # celery-beat:
  #   build:
  #     context: .
  #   container_name: celery_beat
  #   command: celery -A techcity beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #   restart: always
