# Generated by Django 4.2.16 on 2025-01-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('company', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vattransaction',
            name='purchase_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.customer'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='payment_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_stock_transactions', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='salesreturns',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.invoice'),
        ),
    ]
