# Generated by Django 4.2.16 on 2025-05-21 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = []
