# Generated by Django 4.2.16 on 2024-11-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_category_inventory_tax_type_and_more'),
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory'),
        ),
    ]
