# Generated by Django 4.2.16 on 2025-08-28 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0002_branch_disable"),
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[("Customer", "Customer"), ("Supplier", "Supplier")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_note_number", models.CharField(max_length=50, unique=True)),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("receipt_hash", models.TextField(blank=True, null=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                ("signature_data", models.CharField(max_length=50, null=True)),
                ("code", models.CharField(max_length=50, null=True)),
                ("zimra_inv_id", models.CharField(max_length=255, null=True)),
                ("fiscal_day", models.IntegerField(null=True)),
                ("credit_note_invoice_number", models.CharField(max_length=10)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="company.branch"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="sales", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ValueAddedTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("tax_id", models.IntegerField()),
                ("tax_percent", models.FloatField(blank=True, null=True)),
                ("tax_code", models.CharField(max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="cash_up_status",
            new_name="has_reminder",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="recurrence_unit",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="recurrence_value",
        ),
        migrations.AddField(
            model_name="cashbook",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_cashbook",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cashbook",
            name="income",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.income",
            ),
        ),
        migrations.AddField(
            model_name="cashbook",
            name="transfer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.cashtransfers",
            ),
        ),
        migrations.AddField(
            model_name="cashbook",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cashbook",
            name="updated_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_cashbook",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cashup",
            name="cashed_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cashup",
            name="short_fall",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="expense",
            name="account_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="is_loan",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="reminder_dated",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="income",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="from_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="income",
            name="remainder_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="income",
            name="reminder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="income",
            name="to_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="zimra_inv_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="credit_note_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="credit_note_issued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="layby",
            name="amount_due",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="layby",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="layby",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank", "Bank Transfer"),
                    ("ecocash", "EcoCash"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paylater",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.branch",
            ),
        ),
        migrations.AlterField(
            model_name="cashbook",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.currency",
            ),
        ),
        migrations.AlterField(
            model_name="cashbook",
            name="issue_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cashbooknote",
            name="entry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="finance.cashbook",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="is_recurring",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.incomecategory",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="note",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="fiscal_day",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="products_purchased",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="paylater",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paylater",
                to="finance.invoice",
            ),
        ),
        migrations.CreateModel(
            name="Recurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recurrence_value",
                    models.PositiveIntegerField(
                        help_text="Number of units between each recurrence (e.g., every 2 weeks)"
                    ),
                ),
                (
                    "recurrence_unit",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField(blank=True, null=True)),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence",
                        to="finance.expense",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="paylaterDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                ("due_date", models.DateField(null=True)),
                ("paid", models.BooleanField(default=False)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank Transfer"),
                            ("ecocash", "EcoCash"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "paylater",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.paylater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_repayment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "loan_interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Interest rate as a percentage",
                        max_digits=5,
                    ),
                ),
                ("loan_period_value", models.PositiveIntegerField()),
                (
                    "loan_period_unit",
                    models.CharField(
                        choices=[
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan",
                        to="finance.expense",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditNoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vat_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_return", models.BooleanField(default=False)),
                (
                    "credit_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.creditnote",
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.invoiceitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="creditnote",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_notes",
                to="finance.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.invoicecategory",
            ),
        ),
    ]
