# Generated by Django 4.2.16 on 2025-10-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="credit_note_issued",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
