# Generated by Django 4.2.16 on 2025-03-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="receiptServerSignature",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
