# Generated by Django 5.2.1 on 2025-10-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_invoiceitem_credit_note_issued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
