# Generated by Django 4.2.16 on 2025-08-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_contact_creditnote_invoicecategory_valueaddedtax_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="cash_up_status",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="zimra_inv_id",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="fiscal_day",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
