# Generated by Django 4.2.16 on 2025-03-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_invoice_qr_code_invoice_receiptserversignature"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="receipt_hash",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="receiptServerSignature",
            field=models.TextField(blank=True, null=True),
        ),
    ]
