# Generated by Django 4.2.16 on 2025-08-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_remove_invoice_cash_up_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="zimra_inv_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="fiscal_day",
            field=models.IntegerField(null=True),
        ),
    ]
