# Generated by Django 4.2.16 on 2025-01-21 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_alter_cashup_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashflow",
            name="cash_up",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.cashup",
            ),
        ),
    ]
