# Generated by Django 4.2.16 on 2025-03-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_invoice_receipt_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="signature_data",
            field=models.CharField(max_length=50, null=True, verbose_name=""),
        ),
    ]
