# Generated by Django 4.2.16 on 2025-02-14 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_expensesubcategory_incomesubcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashflow",
            name="name",
        ),
        migrations.DeleteModel(
            name="CashFlowName",
        ),
    ]
