# Generated by Django 4.2.16 on 2025-05-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_cashbook_created_by_cashbook_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashbook",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.currency",
            ),
        ),
    ]
