# Generated by Django 4.2.16 on 2025-02-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_remove_cashflow_name_delete_cashflowname"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashFlowName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name_plural": "cashflow_name",
            },
        ),
        migrations.AddField(
            model_name="cashflow",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.cashflowname",
            ),
        ),
    ]
