# Generated by Django 4.2.16 on 2025-04-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_invoice_signature_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="signature_data",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
