# Generated by Django 4.2.16 on 2025-08-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_invoice_cash_up_status_invoice_zimra_inv_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValueAddedTaxx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("tax_id", models.IntegerField()),
                ("tax_percent", models.FloatField(blank=True, null=True)),
                ("tax_code", models.CharField(max_length=3)),
            ],
        ),
    ]
