# Generated by Django 4.2.16 on 2025-01-21 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_cashflow_cash_up"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashflow",
            name="sales",
        ),
    ]
