# Generated by Django 4.2.16 on 2025-04-03 16:37

import apps.finance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_deliverynote_deliverynoteitem"),
        ("finance", "0006_alter_invoice_signature_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="receipt",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.finance.models.expense_receipt_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="finance.expensecategory",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.purchaseorder",
            ),
        ),
    ]
