# Generated by Django 4.2.16 on 2025-01-21 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0006_remove_cashflow_sales"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="debit",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="reference_number",
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="expense",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="income",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="finance.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_type", models.CharField(max_length=50)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_credits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_debits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_transaction_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
