# Generated by Django 4.2.16 on 2025-08-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_valueaddedtaxx"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ValueAddedTaxx",
        ),
    ]
