# Generated by Django 4.2.16 on 2025-02-14 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_cashflowname_cashflow_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainexpensecategory",
            name="sub_expense",
        ),
        migrations.RemoveField(
            model_name="mainincomecategory",
            name="sub_income_category",
        ),
        migrations.RemoveField(
            model_name="cashflow",
            name="expense_category",
        ),
        migrations.RemoveField(
            model_name="cashflow",
            name="income_category",
        ),
        migrations.RemoveField(
            model_name="cashflow",
            name="name",
        ),
        migrations.DeleteModel(
            name="CashFlowName",
        ),
        migrations.DeleteModel(
            name="ExpenseSubCategory",
        ),
        migrations.DeleteModel(
            name="IncomeSubCategory",
        ),
        migrations.DeleteModel(
            name="MainExpenseCategory",
        ),
        migrations.DeleteModel(
            name="MainIncomeCategory",
        ),
    ]
