# Generated by Django 4.2.16 on 2025-02-14 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_remove_mainexpensecategory_sub_expense_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashFlowName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name_plural": "cashflow_name",
            },
        ),
        migrations.CreateModel(
            name="ExpenseSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Expenses Sub Categories",
            },
        ),
        migrations.CreateModel(
            name="IncomeSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Income Sub Categories",
            },
        ),
        migrations.CreateModel(
            name="MainIncomeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "sub_income_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.incomesubcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Income Main Categories",
            },
        ),
        migrations.CreateModel(
            name="MainExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "sub_expense",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.expensesubcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Expenses Main Categories",
            },
        ),
        migrations.AddField(
            model_name="cashflow",
            name="expense_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.mainexpensecategory",
            ),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="income_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.mainincomecategory",
            ),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.cashflowname",
            ),
        ),
    ]
