# Generated by Django 5.2.1 on 2025-05-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_cashup_cashed_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashup",
            name="short_fall",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
