# Generated by Django 4.2.16 on 2025-08-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_delete_valueaddedtaxx_invoice_cash_up_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="valueaddedtax",
            name="name",
        ),
        migrations.RemoveField(
            model_name="valueaddedtax",
            name="tax_code",
        ),
        migrations.RemoveField(
            model_name="valueaddedtax",
            name="tax_id",
        ),
        migrations.RemoveField(
            model_name="valueaddedtax",
            name="tax_percent",
        ),
        migrations.AddField(
            model_name="invoice",
            name="cash_up_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
