# Generated by Django 4.2.16 on 2025-08-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_remove_valueaddedtax_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="valueaddedtax",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="valueaddedtax",
            name="tax_code",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="valueaddedtax",
            name="tax_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="valueaddedtax",
            name="tax_percent",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
