# Generated by Django 4.2.16 on 2025-02-17 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_cashflowname_expensesubcategory_incomesubcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashflow",
            name="expense_category",
        ),
        migrations.RemoveField(
            model_name="cashflow",
            name="income_category",
        ),
    ]
