# Generated by Django 4.2.16 on 2025-04-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_incomecategory_income"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
