# Generated by Django 5.2.1 on 2025-05-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_cashup_short_fall"),
    ]

    operations = [
        migrations.CreateModel(
            name="LossAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_credits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_debits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_transaction_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
