# Generated by Django 4.2.16 on 2025-01-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_remove_transaction_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertransaction",
            name="credit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="usertransaction",
            name="debit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
