# Generated by Django 4.2.16 on 2025-05-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_cashup_short_fall"),
    ]

    operations = [
        migrations.CreateModel(
            name="paylaterDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                ("due_date", models.DateField(auto_now_add=True)),
                ("paid", models.BooleanField(default=False)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank Transfer"),
                            ("ecocash", "EcoCash"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "paylater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.paylater",
                    ),
                ),
            ],
        ),
    ]
