# Generated by Django 5.2.1 on 2025-05-26 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0009_lossaccount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lossaccount",
            old_name="total_credits",
            new_name="amount",
        ),
        migrations.RemoveField(
            model_name="lossaccount",
            name="total_debits",
        ),
        migrations.AddField(
            model_name="lossaccount",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
