# Generated by Django 4.2.16 on 2025-08-28 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_remove_inventory_tax_type"),
        ("finance", "0009_valueaddedtax_name_valueaddedtax_tax_code_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ValueAddedTax",
        ),
    ]
