# Generated by Django 4.2.16 on 2025-04-07 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0009_alter_income_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="finance.incomecategory"
            ),
        ),
    ]
