# Generated by Django 4.2.16 on 2025-08-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_delete_valueaddedtax"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValueAddedTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("tax_id", models.IntegerField(null=True)),
                ("tax_percent", models.FloatField(blank=True, null=True)),
                ("tax_code", models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
