# Generated by Django 4.2.16 on 2025-02-17 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_cashflow_expense_category_cashflow_income_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashflow",
            name="income_category",
        ),
    ]
