# Generated by Django 4.2.16 on 2025-04-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_alter_income_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="issue_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
