# Generated by Django 4.2.16 on 2025-05-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_paylaterdates_amount_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paylaterdates",
            name="due_date",
            field=models.DateField(null=True),
        ),
    ]
