# Generated by Django 4.2.16 on 2025-01-22 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_usertransaction_received_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertransaction",
            name="account",
        ),
        migrations.RemoveField(
            model_name="usertransaction",
            name="received_by",
        ),
        migrations.DeleteModel(
            name="UserAccount",
        ),
        migrations.DeleteModel(
            name="UserTransaction",
        ),
    ]
