# Generated by Django 4.2.16 on 2025-08-29 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0011_valueaddedtax"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditnoteitem",
            name="credit_note",
        ),
        migrations.RemoveField(
            model_name="creditnoteitem",
            name="invoice_item",
        ),
        migrations.DeleteModel(
            name="CreditNote",
        ),
        migrations.DeleteModel(
            name="CreditNoteItem",
        ),
    ]
