# Generated by Django 4.2.16 on 2025-05-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_branch_disable"),
        ("finance", "0011_alter_paylaterdates_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="paylater",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.branch",
            ),
        ),
    ]
