# Generated by Django 4.2.16 on 2025-04-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0011_alter_expense_issue_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
