# Generated by Django 5.2.1 on 2025-05-27 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_paylaterdates_amount_paid"),
        ("finance", "0011_bankaccount_bankaccounttransaction"),
    ]

    operations = []
