# Generated by Django 4.2.16 on 2025-04-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0012_financelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="expenses",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.expense",
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="sale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.invoice",
            ),
        ),
    ]
