# Generated by Django 4.2.16 on 2025-05-28 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0012_paylater_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashbook",
            name="status",
        ),
    ]
