# Generated by Django 4.2.16 on 2025-02-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_branch_disable"),
        ("finance", "0013_cashflow_expense_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="layby",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.branch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="laybydates",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
