# Generated by Django 5.2.1 on 2025-05-27 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0013_bankaccount_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paylater",
            name="amount_due",
        ),
        migrations.RemoveField(
            model_name="paylater",
            name="amount_paid",
        ),
        migrations.RemoveField(
            model_name="paylater",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="paylater",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="paylater",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="paylater",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="paylaterdates",
            name="amount_due",
        ),
        migrations.RemoveField(
            model_name="paylaterdates",
            name="amount_paid",
        ),
        migrations.RemoveField(
            model_name="paylaterdates",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="paylaterdates",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="paylaterdates",
            name="paylater",
        ),
        migrations.RemoveField(
            model_name="paylaterdates",
            name="payment_method",
        ),
    ]
