# Generated by Django 4.2.16 on 2025-08-29 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0013_creditnote_creditnoteitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="credit_note_amount",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="credit_note_issued",
        ),
    ]
