# Generated by Django 4.2.16 on 2025-05-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0013_remove_cashbook_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbook",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
