# Generated by Django 4.2.16 on 2025-04-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0013_income_expenses_income_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="cash_up_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="income",
            name="sale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.invoiceitem",
            ),
        ),
    ]
