# Generated by Django 5.2.1 on 2025-05-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0014_remove_paylater_amount_due_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paylater",
            name="amount_due",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="paylater",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="paylater",
            name="due_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="paylater",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paylater",
                to="finance.invoice",
            ),
        ),
        migrations.AddField(
            model_name="paylater",
            name="paid",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="paylater",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank", "Bank Transfer"),
                    ("ecocash", "EcoCash"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paylaterdates",
            name="amount_due",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="paylaterdates",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="paylaterdates",
            name="due_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="paylaterdates",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paylaterdates",
            name="paylater",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.paylater",
            ),
        ),
        migrations.AddField(
            model_name="paylaterdates",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank", "Bank Transfer"),
                    ("ecocash", "EcoCash"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
