# Generated by Django 4.2.16 on 2025-08-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0014_remove_invoiceitem_credit_note_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="credit_note_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="credit_note_issued",
            field=models.BooleanField(default=False),
        ),
    ]
