# Generated by Django 4.2.16 on 2025-04-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0014_invoiceitem_cash_up_status_alter_income_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="recurrence_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "Day(s)"),
                    ("week", "Week(s)"),
                    ("month", "Month(s)"),
                    ("year", "Year(s)"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="recurrence_value",
            field=models.PositiveIntegerField(
                blank=True, help_text="Repeat every X units", null=True
            ),
        ),
    ]
