# Generated by Django 4.2.16 on 2025-02-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0014_layby_branch_laybydates_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="layby",
            name="fully_paid",
            field=models.BooleanField(default=False),
        ),
    ]
