# Generated by Django 5.2.1 on 2025-05-28 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0014_cashbook_status"),
        ("finance", "0015_paylater_amount_due_paylater_amount_paid_and_more"),
    ]

    operations = []
