# Generated by Django 4.2.16 on 2025-04-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0015_expense_is_recurring_expense_recurrence_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="income",
            name="recurrence_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "Day(s)"),
                    ("week", "Week(s)"),
                    ("month", "Month(s)"),
                    ("year", "Year(s)"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="recurrence_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
