# Generated by Django 4.2.16 on 2025-02-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0015_layby_fully_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="laybydates",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
