# Generated by Django 4.2.16 on 2025-10-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0015_invoiceitem_credit_note_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="tin",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="vat",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
