# Generated by Django 4.2.16 on 2025-02-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0016_laybydates_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="laybydates",
            name="amount_to_be_paid",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
