# Generated by Django 4.2.16 on 2025-10-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0016_invoice_tin_alter_invoice_vat"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="vat_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="vat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
