# Generated by Django 4.2.16 on 2025-04-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0016_income_is_recurring_income_recurrence_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashup",
            name="expenses_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cashup",
            name="sales_status",
            field=models.BooleanField(default=False),
        ),
    ]
