# Generated by Django 5.2.1 on 2025-05-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0016_merge_20250528_1658"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paylater",
            name="due_date",
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paylater",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
