# Generated by Django 4.2.16 on 2025-04-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0017_cashup_expenses_status_cashup_sales_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashup",
            name="sales",
            field=models.ManyToManyField(
                related_name="cashup_sales", to="finance.invoice"
            ),
        ),
    ]
