# Generated by Django 5.2.1 on 2025-05-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0017_alter_paylater_due_date_alter_paylater_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashbook",
            name="issue_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
