# Generated by Django 4.2.16 on 2025-04-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0017_cashup_expenses_status_cashup_sales_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="code",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
