# Generated by Django 4.2.16 on 2025-11-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0018_taxconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxconfiguration",
            name="code",
            field=models.CharField(default="A", max_length=100),
            preserve_default=False,
        ),
    ]
