# Generated by Django 4.2.16 on 2025-04-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0018_invoice_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="fiscal_day",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
