# Generated by Django 4.2.16 on 2025-04-28 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0018_alter_cashup_sales"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashup",
            name="sales",
        ),
    ]
