# Generated by Django 5.2.1 on 2025-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0018_alter_cashbook_issue_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="layby",
            name="amount_due",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="layby",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="layby",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank", "Bank Transfer"),
                    ("ecocash", "EcoCash"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
