# Generated by Django 4.2.16 on 2025-02-20 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0019_laybydates_payment_method_paylater"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paylater",
            name="user",
        ),
    ]
