# Generated by Django 4.2.16 on 2025-04-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0019_remove_cashup_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashup",
            name="sales",
            field=models.ManyToManyField(
                related_name="cashup_sales", to="finance.invoice"
            ),
        ),
    ]
