# Generated by Django 5.2.1 on 2025-06-09 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0019_layby_amount_due_layby_amount_paid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="products_purchased",
        ),
    ]
