# Generated by Django 4.2.16 on 2025-11-27 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0019_taxconfiguration_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaxConfiguration",
        ),
    ]
