# Generated by Django 4.2.16 on 2025-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0019_invoice_fiscal_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
