# Generated by Django 5.2.1 on 2025-06-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0020_remove_invoice_products_purchased"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="products_purchased",
            field=models.TextField(null=True),
        ),
    ]
