# Generated by Django 4.2.16 on 2025-04-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0020_cashup_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cash_up_status",
            field=models.BooleanField(default=False),
        ),
    ]
