# Generated by Django 4.2.16 on 2025-02-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0020_remove_paylater_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laybydates",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank", "Bank Transfer"),
                    ("ecocash", "EcoCash"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paylater",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank", "Bank Transfer"),
                    ("ecocash", "EcoCash"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
