# Generated by Django 4.2.16 on 2025-04-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0020_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="cash_up_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
