# Generated by Django 4.2.16 on 2025-11-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0020_delete_taxconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_id", models.IntegerField(unique=True)),
                ("tax_name", models.CharField(max_length=100)),
                (
                    "tax_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
            ],
        ),
    ]
