# Generated by Django 4.2.16 on 2025-04-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0021_alter_invoiceitem_cash_up_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cash_up_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
