# Generated by Django 4.2.16 on 2025-02-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0021_alter_laybydates_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paylater",
            name="due_date",
            field=models.DateField(),
        ),
    ]
