# Generated by Django 4.2.16 on 2025-05-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0021_invoice_cash_up_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="sale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.invoice",
            ),
        ),
    ]
