# Generated by Django 4.2.16 on 2025-05-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0021_invoice_cash_up_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="sale",
        ),
        migrations.AddField(
            model_name="income",
            name="sale",
            field=models.ManyToManyField(to="finance.invoice"),
        ),
    ]
