# Generated by Django 4.2.16 on 2025-12-18 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0021_taxconfiguration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ValueAddedTax",
        ),
    ]
