# Generated by Django 5.2.1 on 2025-06-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0021_invoice_products_purchased"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="products_purchased",
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
