# Generated by Django 5.2.1 on 2025-06-09 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0022_alter_invoice_products_purchased"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="note",
        ),
    ]
