# Generated by Django 4.2.16 on 2025-05-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0022_remove_income_sale_income_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="sale",
        ),
        migrations.AddField(
            model_name="income",
            name="sale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.invoice",
            ),
        ),
    ]
