# Generated by Django 4.2.16 on 2025-05-07 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0022_alter_income_sale"),
        ("finance", "0023_remove_income_sale_income_sale"),
    ]

    operations = []
