# Generated by Django 5.2.1 on 2025-06-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0023_remove_invoice_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="note",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
