# Generated by Django 4.2.16 on 2025-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0023_creditnote_creditnoteitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnoteitem",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="creditnoteitem",
            name="is_return",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="creditnoteitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="creditnoteitem",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="creditnoteitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="creditnoteitem",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="creditnoteitem",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
