# Generated by Django 5.2.1 on 2025-06-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0024_alter_income_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="note",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="products_purchased",
            field=models.TextField(null=True),
        ),
    ]
