# Generated by Django 4.2.16 on 2025-05-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0024_merge_20250507_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="cash_up_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
