# Generated by Django 4.2.16 on 2025-05-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0024_creditnoteitem_discount_creditnoteitem_is_return_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnoteitem",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
