# Generated by Django 5.2.1 on 2025-06-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0025_invoice_note_alter_invoice_products_purchased"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
