# Generated by Django 4.2.16 on 2025-05-13 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0022_invoice_cash_up_status"),
        ("finance", "0025_expense_cash_up_status"),
    ]

    operations = []
