# Generated by Django 4.2.16 on 2025-05-28 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0025_creditnoteitem_discount_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditnoteitem",
            name="discount_amount",
        ),
    ]
