# Generated by Django 5.2.1 on 2025-06-16 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0026_useraccount_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="description",
        ),
    ]
