# Generated by Django 4.2.16 on 2025-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0026_remove_creditnoteitem_discount_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbook",
            name="status",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
