# Generated by Django 4.2.16 on 2025-05-28 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0027_cashbook_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashbook",
            name="status",
        ),
    ]
