# Generated by Django 5.2.1 on 2025-06-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0027_remove_useraccount_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountbalance",
            name="negative",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accountbalance",
            name="negative_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="accountbalance",
            name="positive",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accountbalance",
            name="positive_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
