# Generated by Django 5.2.1 on 2025-06-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "finance",
            "0028_accountbalance_negative_accountbalance_negative_cost_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountbalance",
            name="negative",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="positive",
            field=models.IntegerField(default=0),
        ),
    ]
