# Generated by Django 4.2.16 on 2025-05-28 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0029_cashbook_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbook",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cashbook",
            name="updated_by",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_cashbook",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="credit_note_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=15, null=True
            ),
        ),
    ]
