# Generated by Django 5.2.1 on 2025-06-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0030_remove_accountbalance_negative_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="from_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="income",
            name="remainder_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="income",
            name="reminder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="income",
            name="to_date",
            field=models.DateField(null=True),
        ),
    ]
