# Generated by Django 4.2.16 on 2025-05-28 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0030_cashbook_updated_at_cashbook_updated_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="credit_note_amount",
        ),
    ]
