# Generated by Django 4.2.16 on 2025-05-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0031_remove_invoiceitem_credit_note_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="credit_note_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=15, null=True
            ),
        ),
    ]
