# Generated by Django 5.2.1 on 2025-07-07 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0032_income_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbook",
            name="transfer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.cashtransfers",
            ),
        ),
    ]
