# Generated by Django 4.2.16 on 2025-05-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0032_invoiceitem_credit_note_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbook",
            name="status",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.incomecategory",
            ),
        ),
    ]
