# Generated by Django 5.2.1 on 2025-07-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0033_cashbook_transfer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="cash_up_status",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="recurrence_unit",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="recurrence_value",
        ),
        migrations.AddField(
            model_name="expense",
            name="has_reminder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="is_loan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="reminder_dated",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_repayment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "loan_interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Interest rate as a percentage",
                        max_digits=5,
                    ),
                ),
                ("loan_period_value", models.PositiveIntegerField()),
                (
                    "loan_period_unit",
                    models.CharField(
                        choices=[
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan",
                        to="finance.expense",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recurrence_value",
                    models.PositiveIntegerField(
                        help_text="Number of units between each recurrence (e.g., every 2 weeks)"
                    ),
                ),
                (
                    "recurrence_unit",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField(blank=True, null=True)),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence",
                        to="finance.expense",
                    ),
                ),
            ],
        ),
    ]
