# Generated by Django 4.2.16 on 2025-05-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0033_cashbook_status_alter_income_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="credit_note_issued",
            field=models.BooleanField(default=False),
        ),
    ]
