# Generated by Django 5.2.1 on 2025-07-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0034_remove_expense_cash_up_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="account_to",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_to",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
