# Generated by Django 4.2.16 on 2025-05-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0034_invoiceitem_credit_note_issued"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="zimra_inv_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
