# Generated by Django 4.2.16 on 2025-05-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0035_invoice_zimra_inv_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="fiscal_day",
            field=models.IntegerField(null=True),
        ),
    ]
