# Generated by Django 5.2.1 on 2025-07-08 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0035_expense_account_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashbooknote",
            name="entry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="finance.cashbook",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="account_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="has_reminder",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="is_loan",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="is_recurring",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.incomecategory",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="note",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
