# Generated by Django 5.2.1 on 2025-07-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0036_alter_cashbooknote_entry_alter_expense_account_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbook",
            name="income",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.income",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="note",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
