# Generated by Django 4.2.16 on 2025-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0036_alter_invoice_fiscal_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="fiscal_day",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="receipt_hash",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="signature_data",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="zimra_inv_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
