# Generated by Django 5.2.1 on 2025-07-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0037_cashbook_income_alter_income_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[("Customer", "Customer"), ("Supplier", "Supplier")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
