# Generated by Django 4.2.16 on 2025-06-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0037_creditnote_code_creditnote_fiscal_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="credit_note_invoice_number",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
