# Generated by Django 4.2.16 on 2025-06-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0038_creditnote_credit_note_invoice_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValueAddedTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_id", models.IntegerField()),
                ("tax_percent", models.FloatField()),
                ("tax_code", models.CharField(max_length=3)),
            ],
        ),
    ]
