# Generated by Django 5.2.1 on 2025-08-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0038_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="sales", max_length=50)),
            ],
        ),
    ]
