# Generated by Django 4.2.16 on 2025-06-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0039_valueaddedtax"),
    ]

    operations = [
        migrations.AddField(
            model_name="valueaddedtax",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
