# Generated by Django 4.2.16 on 2025-06-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0040_valueaddedtax_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valueaddedtax",
            name="tax_percent",
            field=models.FloatField(null=True),
        ),
    ]
