# Generated by Django 5.2.1 on 2025-09-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0040_invoice_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="credit_note_issued",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
