# Generated by Django 4.2.16 on 2025-08-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0041_alter_valueaddedtax_tax_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valueaddedtax",
            name="tax_percent",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
