# Generated by Django 4.2.16 on 2024-12-06 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='voucherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'voucherCategory',
                'verbose_name_plural': 'voucherCategorys',
            },
        ),
        migrations.CreateModel(
            name='voucherFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='vouchers')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='not populated', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.vouchercategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'voucherFile',
                'verbose_name_plural': 'voucherFiles',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='voucherUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'voucherUser',
                'verbose_name_plural': 'voucherUsers',
            },
        ),
        migrations.CreateModel(
            name='vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_used', models.DateField(auto_now=True)),
                ('status', models.CharField(default='unused', max_length=50)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.voucherfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vouchers',
                'verbose_name_plural': 'vouchers',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='voucherLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'voucherLogs',
                'verbose_name_plural': 'voucherLogss',
                'ordering': ['-date_created'],
            },
        ),
    ]
