# Generated by Django 4.2.16 on 2024-10-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0034_alter_activitylog_action_alter_activitylog_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="dealer_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
