# Generated by Django 4.2.16 on 2024-10-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0035_activitylog_dealer_price_activitylog_selling_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferitems",
            name="dealer_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
