# Generated by Django 4.2.16 on 2024-10-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0036_transferitems_dealer_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="delete",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
