# Generated by Django 4.2.16 on 2024-10-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0039_transferitems_receieved_quanity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferitems",
            name="receieved_quanity",
        ),
        migrations.AddField(
            model_name="transferitems",
            name="receieved_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
