# Generated by Django 4.2.16 on 2024-10-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0040_remove_transferitems_receieved_quanity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferitems",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
