# Generated by Django 4.2.16 on 2024-12-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpermissions_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='category',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
