# Generated by Django 4.2.16 on 2025-01-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_emailverificationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationtoken",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
    ]
