# Generated by Django 4.2.16 on 2025-01-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_branch_disable"),
        ("users", "0007_emailverificationtoken_attempts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="branch",
        ),
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ManyToManyField(to="company.branch"),
        ),
    ]
