# Generated by Django 4.2.16 on 2025-01-16 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_branch_disable"),
        ("users", "0008_remove_user_branch_user_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="branch",
        ),
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.branch",
            ),
        ),
    ]
