# Generated by Django 5.2.1 on 2025-05-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_user_branch_user_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="delete",
            field=models.BooleanField(default=True),
        ),
    ]
