# Generated by Django 5.2.1 on 2025-05-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_delete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="delete",
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
