# Generated by Django 4.2.16 on 2024-11-07 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("stock in", "stock in"),
                            ("Stock update", "Stock update"),
                            ("stock adjustment", "stock adjustment"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("edit", "Edit"),
                            ("transfer", "Transfer"),
                            ("returns", "returns"),
                            ("sale return", "sale return"),
                            ("sale", "Sale"),
                            ("declined", "Declined"),
                            ("write off", "write off"),
                            ("defective", "defective"),
                            ("activated", "activated"),
                            ("deactivated", "deactivated"),
                            ("removed", "removed"),
                            ("purchase edit +", "purchase edit +"),
                            ("purchase edit -", "purchase edit -"),
                            ("transfer cancel", "transfer cancel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("total_quantity", models.IntegerField()),
                (
                    "dealer_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("system_quantity", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=255, null=True)),
            ],
            options={
                "get_latest_by": "timestamp",
            },
        ),
        migrations.CreateModel(
            name="BatchCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="costAllocationPurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocated", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "allocationRate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("expense_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                ("product", models.CharField(max_length=255)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_buying", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="DefectiveProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lost in transit", "Lost in transit"),
                            ("stolen", "stolen"),
                            ("damaged", "Damage"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dealer_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("quantity", models.IntegerField(null=True)),
                ("status", models.BooleanField(default=True, null=True)),
                ("stock_level_threshold", models.IntegerField(default=5, null=True)),
                ("reorder", models.BooleanField(default=False, null=True)),
                (
                    "alert_notification",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("batch", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="otherExpenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch", models.CharField(blank=True, default="", max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("quantity", models.IntegerField(default=0, null=True)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("exempted", "Exempted"),
                            ("standard", "Standard"),
                            ("zero rated", "Zero Rated"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("min_stock_level", models.IntegerField(default=0, null=True)),
                ("description", models.TextField()),
                ("end_of_day", models.BooleanField(default=False, null=True)),
                ("service", models.BooleanField(default=False, null=True)),
                (
                    "dealer_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=100, unique=True)),
                ("order_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ordered", "Ordered"),
                            ("received", "Received"),
                            ("canceled", "Canceled"),
                        ],
                        default="received",
                        max_length=50,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "other_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("is_partial", models.BooleanField(default=False)),
                ("received", models.BooleanField(default=False)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "cash"),
                            ("bank", "bank"),
                            ("ecocash", "ecocash"),
                        ],
                        default="cash",
                        max_length=15,
                    ),
                ),
                ("batch", models.CharField(max_length=20, null=True)),
                ("hold", models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "actual_unit_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("received_quantity", models.IntegerField(default=0)),
                ("received", models.BooleanField(default=False, null=True)),
                (
                    "expected_profit",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "dealer_expected_profit",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReorderList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("quantity", models.IntegerField()),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="reorderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier", models.CharField(max_length=255)),
                ("quantity_suggestion", models.BooleanField(default=False)),
                ("number_of_days_from", models.FloatField(null=True)),
                ("number_of_days_to", models.FloatField(null=True)),
                ("order_enough_stock", models.BooleanField(default=False)),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("exempted", "Exempted"),
                            ("standard", "Standard"),
                            ("zero rated", "Zero Rated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StockNotifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification", models.CharField(max_length=255)),
                ("status", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("stock level", "Stock level"),
                            ("stock take", "stock take"),
                            ("stock transfer", "stock transfer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("address", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_ref", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=266)),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.IntegerField(default=0, null=True)),
                ("total_quantity_track", models.IntegerField(default=0, null=True)),
                ("defective_status", models.BooleanField(default=False)),
                ("delete", models.BooleanField(default=False, null=True)),
                ("receive_status", models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransferItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("date_received", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.IntegerField()),
                ("over_less_quantity", models.IntegerField(default=0, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dealer_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("received", models.BooleanField(default=False)),
                ("declined", models.BooleanField(default=False)),
                ("over_less", models.BooleanField(default=False)),
                ("quantity_track", models.IntegerField(default=0, null=True)),
                (
                    "over_less_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField()),
                ("receieved_quantity", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
