# Generated by Django 4.2.16 on 2024-11-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='tax_type',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='batch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
