# Generated by Django 4.2.16 on 2025-01-18 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('finance', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='accessory_product',
            field=models.ManyToManyField(to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='main_product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='inventory.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='inventory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='product_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.transferitems'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costallocationpurchaseorder',
            name='purchase_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defectiveproduct',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defectiveproduct',
            name='branch_loss',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='loss', to='company.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defectiveproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='holdtransfer',
            name='from_branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='hold_destination', to='company.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holdtransfer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='holdtransfer',
            name='to_branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='hold_source', to='company.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holdtransfer',
            name='transfer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.transfer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='suppliers',
            field=models.ManyToManyField(related_name='products_suppliers', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='otherexpenses',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='products', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='purchase_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseorderitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='supplier',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='reorderlist',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reorderlist',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory'),
        ),
        migrations.AddField(
            model_name='stocknotifications',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='stocknotifications',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.transfer'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='stocktake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stocktake'),
        ),
        migrations.AddField(
            model_name='supplieraccount',
            name='currency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='finance.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplieraccount',
            name='supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplieraccountspayments',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.supplieraccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplieraccountspayments',
            name='currency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='finance.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplieraccountspayments',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_branch', to='company.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_to',
            field=models.ManyToManyField(to='company.branch'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferitems',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='over_less_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferitems',
            name='from_branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='company.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferitems',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='transferitems',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferitems',
            name='to_branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='source', to='company.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferitems',
            name='transfer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.transfer'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('id', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='supplieraccount',
            unique_together={('currency', 'supplier')},
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['branch'], name='inventory_t_branch__4294ec_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['transfer_ref'], name='inventory_t_transfe_562f35_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['date'], name='inventory_t_date_e1402d_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['delete'], name='inventory_t_delete_4e2df1_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['hold'], name='inventory_t_hold_41b549_idx'),
        ),
    ]
