# Generated by Django 4.2.16 on 2024-12-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['branch'], name='inventory_t_branch__4294ec_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['transfer_ref'], name='inventory_t_transfe_562f35_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['date'], name='inventory_t_date_e1402d_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['delete'], name='inventory_t_delete_4e2df1_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['hold'], name='inventory_t_hold_41b549_idx'),
        ),
    ]
