# Generated by Django 4.2.16 on 2024-11-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('company', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplieraccount',
            unique_together={('currency', 'supplier')},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplieraccount',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'supplier')},
        ),
        migrations.CreateModel(
            name='Holdtransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(null=True)),
                ('dealer_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_destination', to='company.branch')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_source', to='company.branch')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.transfer')),
            ],
        ),
    ]
