# Generated by Django 4.2.16 on 2024-11-25 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="delete",
        ),
    ]
