# Generated by Django 4.2.16 on 2024-11-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="suppliers",
            field=models.ManyToManyField(
                null=True, related_name="products", to="inventory.supplier"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
