# Generated by Django 4.2.16 on 2025-03-17 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverynote",
            name="delivery_date",
        ),
        migrations.RemoveField(
            model_name="deliverynote",
            name="pdf",
        ),
        migrations.RemoveField(
            model_name="deliverynote",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="deliverynote",
            name="received_by",
        ),
        migrations.AddField(
            model_name="deliverynoteitem",
            name="delivery_note",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventory.deliverynote",
            ),
        ),
        migrations.AddField(
            model_name="deliverynoteitem",
            name="product_name",
            field=models.CharField(default="casy", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliverynoteitem",
            name="quantity_delivered",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
