# Generated by Django 4.2.16 on 2024-12-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_transfer_inventory_t_branch__4294ec_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferitems',
            old_name='receieved_quantity',
            new_name='received_quantity',
        ),
    ]
