# Generated by Django 4.2.16 on 2024-11-09 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_product_suppliers_alter_supplier_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="suppliers",
        ),
    ]
