# Generated by Django 4.2.18 on 2025-02-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_accessory_accessory_product_accessory_main_product_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transfer',
            name='inventory_t_hold_41b549_idx',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='result',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='s_t_number',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='hold',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_to',
        ),
        migrations.RemoveField(
            model_name='transferitems',
            name='received_quantity',
        ),
    ]
