# Generated by Django 4.2.16 on 2025-08-28 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_contact_creditnote_invoicecategory_valueaddedtax_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0002_branch_disable"),
        ("inventory", "0002_temporarypurchaseorder_temporarypurchaseorderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("low_stock", models.BooleanField(default=True)),
                ("out_of_stock", models.BooleanField(default=True)),
                ("movement_create", models.BooleanField(default=True)),
                ("movement_update", models.BooleanField(default=True)),
                ("movement_delete", models.BooleanField(default=True)),
                ("movement_transfer", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="temporarypurchaseorderitem",
            name="date",
        ),
        migrations.AddField(
            model_name="activitylog",
            name="stocktake",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.stocktake",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="name",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="conducted_by",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="conductor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocktake_conductor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="negative",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="negative_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="positive",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="positive_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="accepted",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="company_loss",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="has_diff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="note",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="now_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="recorded",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorder",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.branch",
            ),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorder",
            name="name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorder",
            name="order_number",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="actual_unit_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="dealer_expected_profit",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="expected_profit",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="received",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="received_quantity",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="wholesale_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("stock in", "stock in"),
                    ("Stock update", "Stock update"),
                    ("stock adjustment", "stock adjustment"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("edit", "Edit"),
                    ("transfer in", "transfer in"),
                    ("transfer out", "transfer out"),
                    ("returns", "returns"),
                    ("sale return", "sale return"),
                    ("sale", "Sale"),
                    ("declined", "Declined"),
                    ("write off", "write off"),
                    ("defective", "defective"),
                    ("activated", "activated"),
                    ("deactivated", "deactivated"),
                    ("removed", "removed"),
                    ("purchase edit +", "purchase edit +"),
                    ("purchase edit -", "purchase edit -"),
                    ("transfer cancel", "transfer cancel"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="tax_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.valueaddedtax",
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="temporarypurchaseorderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="temporarypurchaseorderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="temporarypurchaseorderitem",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="temporarypurchaseorderitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.supplier",
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["branch", "status", "disable"],
                name="inventory_i_branch__66a381_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["name"], name="inventory_i_name_43f130_idx"),
        ),
        migrations.AddField(
            model_name="inventorynotificationsettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
