# Generated by Django 5.2.1 on 2025-05-28 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_temporarypurchaseorder_temporarypurchaseorderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporarypurchaseorderitem",
            name="temporary_purchase_order",
        ),
        migrations.RemoveField(
            model_name="temporarypurchaseorderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="temporarypurchaseorderitem",
            name="supplier",
        ),
        migrations.DeleteModel(
            name="TemporaryPurchaseOrder",
        ),
        migrations.DeleteModel(
            name="TemporaryPurchaseOrderItem",
        ),
    ]
