# Generated by Django 4.2.16 on 2024-11-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_category_remove_inventory_tax_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='tax_type',
            field=models.CharField(choices=[('exempted', 'Exempted'), ('standard', 'Standard'), ('zero rated', 'Zero Rated')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
