# Generated by Django 4.2.16 on 2024-11-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplieraccount_alter_product_suppliers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='products', to='inventory.supplier'),
        ),
    ]
