# Generated by Django 4.2.16 on 2024-11-25 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_inventory_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="product",
        ),
    ]
