# Generated by Django 4.2.16 on 2024-11-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_ref',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_to',
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_to',
            field=models.ManyToManyField(to='company.branch'),
        ),
    ]
