# Generated by Django 4.2.16 on 2025-03-05 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_remove_purchaseorder_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="batch",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="hold",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="is_partial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="other_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "cash"), ("bank", "bank"), ("ecocash", "ecocash")],
                default="cash",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="received",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ordered", "Ordered"),
                    ("received", "Received"),
                    ("canceled", "Canceled"),
                ],
                default="received",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
