# Generated by Django 4.2.16 on 2025-03-17 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_remove_deliverynote_delivery_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="delivery_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="delivery_notes/"),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="purchase_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_notes",
                to="inventory.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="received_by",
            field=models.CharField(default="casy", max_length=255),
            preserve_default=False,
        ),
    ]
