# Generated by Django 4.2.16 on 2024-11-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_remove_product_suppliers"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="suppliers",
            field=models.ManyToManyField(
                null=True, related_name="products", to="inventory.supplier"
            ),
        ),
    ]
