# Generated by Django 4.2.16 on 2024-11-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_supplier_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferitems",
            name="transfer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.product"
            ),
        ),
    ]
