# Generated by Django 4.2.16 on 2025-03-05 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_purchaseorder_batch_purchaseorder_delivery_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="delivery_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="hold",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="is_partial",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="order_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="order_number",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="other_amount",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="received",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="status",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="total_cost",
        ),
    ]
