# Generated by Django 4.2.16 on 2024-11-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_remove_inventory_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferitems",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.inventory",
            ),
        ),
    ]
