# Generated by Django 4.2.16 on 2025-03-17 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_deliverynote_delivery_date_deliverynote_pdf_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverynote",
            name="delivery_date",
        ),
        migrations.RemoveField(
            model_name="deliverynote",
            name="pdf",
        ),
        migrations.RemoveField(
            model_name="deliverynote",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="deliverynote",
            name="received_by",
        ),
        migrations.RemoveField(
            model_name="deliverynoteitem",
            name="delivery_note",
        ),
        migrations.RemoveField(
            model_name="deliverynoteitem",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="deliverynoteitem",
            name="quantity_delivered",
        ),
    ]
