# Generated by Django 4.2.18 on 2025-02-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0003_remove_transfer_inventory_t_hold_41b549_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfer_to',
            field=models.ManyToManyField(null=True, to='company.branch'),
        ),
    ]
