# Generated by Django 4.2.16 on 2024-11-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
    ]
