# Generated by Django 4.2.16 on 2024-11-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_transferitems_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tax_type",
        ),
        migrations.AddField(
            model_name="inventory",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="tax_type",
            field=models.CharField(
                choices=[
                    ("exempted", "Exempted"),
                    ("standard", "Standard"),
                    ("zero rated", "Zero Rated"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
