# Generated by Django 4.2.16 on 2025-03-05 15:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_branch_disable"),
        ("inventory", "0004_remove_purchaseorder_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="batch",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.branch",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="hold",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="is_partial",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="other_amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "cash"), ("bank", "bank"), ("ecocash", "ecocash")],
                default="cash",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="received",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ordered", "Ordered"),
                    ("received", "Received"),
                    ("canceled", "Canceled"),
                ],
                default="received",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="actual_unit_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="dealer_expected_profit",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="expected_profit",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.inventory",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="purchase_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventory.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="received",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="received_quantity",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.supplier",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="wholesale_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
