# Generated by Django 4.2.18 on 2025-02-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0004_transfer_transfer_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_to',
            field=models.ManyToManyField(to='company.branch'),
        ),
    ]
