# Generated by Django 4.2.16 on 2024-11-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0004_alter_product_description_alter_service_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="supplier",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.supplier",
            ),
        ),
    ]
