# Generated by Django 4.2.16 on 2024-11-25 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_transferitems_transfer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferitems",
            name="product",
        ),
    ]
