# Generated by Django 5.2.1 on 2025-05-28 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_temporarypurchaseorder_temporarypurchaseorderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporarypurchaseorderitem",
            name="date",
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="actual_unit_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="dealer_expected_profit",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="expected_profit",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="received",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="received_quantity",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorderitem",
            name="wholesale_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="temporarypurchaseorderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="temporarypurchaseorderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="temporarypurchaseorderitem",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="temporarypurchaseorderitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.supplier",
            ),
        ),
    ]
