# Generated by Django 5.2.1 on 2025-05-28 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_branch_disable"),
        ("inventory", "0005_remove_temporarypurchaseorderitem_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporarypurchaseorder",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.branch",
            ),
        ),
        migrations.AddField(
            model_name="temporarypurchaseorder",
            name="order_number",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
