# Generated by Django 4.2.16 on 2024-11-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_remove_product_category_remove_product_tax_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="batch",
        ),
        migrations.AddField(
            model_name="inventory",
            name="description",
            field=models.TextField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="inventory",
            name="suppliers",
            field=models.ManyToManyField(
                related_name="products_suppliers", to="inventory.supplier"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="batch",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
