# Generated by Django 4.2.16 on 2025-03-17 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_deliverynote_delivery_date_deliverynote_pdf_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverynoteitem",
            name="delivery_note",
        ),
        migrations.DeleteModel(
            name="DeliveryNote",
        ),
        migrations.DeleteModel(
            name="DeliveryNoteItem",
        ),
    ]
