# Generated by Django 4.2.16 on 2025-08-28 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_inventory_tax_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="tax_type",
        ),
    ]
