# Generated by Django 4.2.16 on 2024-11-25 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_remove_transferitems_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferitems",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.inventory",
            ),
        ),
    ]
