# Generated by Django 4.2.16 on 2024-11-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_purchaseorderitem_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.supplier",
            ),
        ),
    ]
