# Generated by Django 4.2.16 on 2024-11-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
        ("inventory", "0005_supplieraccount_supplieraccountspayments"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplieraccount",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplieraccountspayments",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplieraccountspayments",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "cash"), ("bank", "bank"), ("ecocash", "ecocash")],
                default=1,
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
