# Generated by Django 4.2.16 on 2024-11-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_transferitems_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferitems",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.product",
            ),
        ),
        migrations.AlterField(
            model_name="transferitems",
            name="transfer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.transfer"
            ),
        ),
    ]
