# Generated by Django 4.2.16 on 2024-11-25 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        ("inventory", "0006_remove_product_batch_inventory_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="delete",
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("id", "branch")},
        ),
    ]
