# Generated by Django 4.2.16 on 2025-03-17 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_remove_deliverynoteitem_delivery_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_date", models.DateField(null=True)),
                ("received_by", models.CharField(max_length=255, null=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="delivery_notes/"
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_notes",
                        to="inventory.purchaseorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryNoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255, null=True)),
                ("quantity_delivered", models.PositiveIntegerField(null=True)),
                (
                    "delivery_note",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.deliverynote",
                    ),
                ),
            ],
        ),
    ]
