<<<<<<< HEAD
# Generated by Django 4.2.16 on 2024-11-14 09:16
=======
# Generated by Django 4.2.16 on 2024-11-14 08:40
>>>>>>> 9653a2daed53fee3bbe0d2b5199727821e11a90b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_purchaseorderitem_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
