# Generated by Django 5.2.1 on 2025-05-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_temporarypurchaseorder_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporarypurchaseorder",
            name="name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
