# Generated by Django 4.2.16 on 2025-01-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchaseorderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='serial_numbers',
            field=models.ManyToManyField(related_name='inventories', to='inventory.serialnumber'),
        ),
    ]
