# Generated by Django 4.2.16 on 2025-03-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_deliverynote_deliverynoteitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="delivery_note_pdf",
            field=models.FileField(blank=True, null=True, upload_to="delivery_notes/"),
        ),
    ]
