# Generated by Django 4.2.16 on 2025-06-25 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_deliverynote_deliverynoteitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="tax_type",
        ),
    ]
