# Generated by Django 4.2.16 on 2025-03-05 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_deliverynote_delivery_note_pdf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliverynote",
            old_name="delivery_note_pdf",
            new_name="pdf",
        ),
    ]
