# Generated by Django 4.2.18 on 2025-02-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_transfer_to_id_transfer_transfer_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='transfer_to',
            new_name='transfer_to_id',
        ),
    ]
