# Generated by Django 4.2.16 on 2024-11-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_remove_supplier_delete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="delete",
            field=models.BooleanField(default=False),
        ),
    ]
