# Generated by Django 4.2.16 on 2025-11-27 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_alter_inventory_tax_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="tax_type",
        ),
    ]
