# Generated by Django 4.2.16 on 2025-06-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0039_valueaddedtax"),
        ("inventory", "0008_remove_inventory_tax_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="tax_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.valueaddedtax",
            ),
        ),
    ]
