# Generated by Django 4.2.16 on 2024-11-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stocktake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
