# Generated by Django 4.2.16 on 2025-01-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_writeoff_inventoryshrinkage_defectiveitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryshrinkage',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='inventoryshrinkage',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='writeoff',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='writeoff',
            name='inventory_item',
        ),
        migrations.DeleteModel(
            name='DefectiveItem',
        ),
        migrations.DeleteModel(
            name='InventoryShrinkage',
        ),
        migrations.DeleteModel(
            name='WriteOff',
        ),
    ]
