# Generated by Django 4.2.18 on 2025-02-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_transfer_to_transfer_transfer_to_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='transfer_to_id',
            new_name='transfer_to',
        ),
    ]
