# Generated by Django 4.2.16 on 2024-11-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_alter_purchaseorderitem_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.supplier",
            ),
        ),
    ]
