# Generated by Django 4.2.16 on 2025-06-27 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_inventory_tax_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="serial_numbers",
        ),
    ]
