# Generated by Django 4.2.16 on 2025-11-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0021_taxconfiguration"),
        ("inventory", "0009_remove_inventory_tax_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="tax_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.taxconfiguration",
            ),
        ),
    ]
