# Generated by Django 4.2.16 on 2024-11-25 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_accessory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Accessory",
        ),
    ]
