# Generated by Django 5.2.1 on 2025-06-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_stocktake_conductor_stocktake_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktake",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
