# Generated by Django 5.2.1 on 2025-06-14 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_alter_stocktake_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stocktake",
            old_name="users",
            new_name="conducted_by",
        ),
    ]
