# Generated by Django 4.2.16 on 2024-11-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_supplier_address'),
        ('inventory', '0010_alter_purchaseorderitem_supplier'),
    ]

    operations = [
    ]
