# Generated by Django 4.2.16 on 2024-11-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_accessory"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="end_of_day",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="service",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
