# Generated by Django 5.2.1 on 2025-06-14 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_rename_users_stocktake_conducted_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktake",
            name="conducted_by",
        ),
        migrations.AddField(
            model_name="stocktake",
            name="conducted_by",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
