# Generated by Django 4.2.16 on 2024-11-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_inventory_end_of_day_inventory_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="product_images/"),
        ),
    ]
