# Generated by Django 5.2.1 on 2025-06-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_remove_stocktake_conducted_by_stocktake_conducted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktakeitem",
            name="cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
