# Generated by Django 4.2.16 on 2025-01-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_writeoff_inventoryshrinkage_defectiveitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferitems',
            name='defect_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
