# Generated by Django 4.2.16 on 2024-11-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="image",
            field=models.ImageField(null=True, upload_to="product_images/"),
        ),
    ]
