# Generated by Django 4.2.16 on 2024-11-15 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
        ("inventory", "0013_supplier_address"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="supplieraccount",
            unique_together={("currency",)},
        ),
    ]
