# Generated by Django 4.2.16 on 2025-01-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_transferitems_defect_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferitems',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferitems',
            name='received_back_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
