# Generated by Django 4.2.16 on 2025-01-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_transferitems_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferitems',
            name='defect_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transferitems',
            name='received_back_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
