# Generated by Django 4.2.16 on 2024-11-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_inventory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="image",
            field=models.ImageField(
                default="placeholder.png", null=True, upload_to="product_images/"
            ),
        ),
    ]
