# Generated by Django 4.2.16 on 2024-11-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_alter_inventory_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accessory",
            old_name="product",
            new_name="accessory_product",
        ),
        migrations.AddField(
            model_name="accessory",
            name="main_product",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_product",
                to="inventory.inventory",
            ),
            preserve_default=False,
        ),
    ]
