# Generated by Django 5.2.1 on 2025-06-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_alter_stocktakeitem_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktakeitem",
            name="accepted",
            field=models.BooleanField(default=True),
        ),
    ]
