# Generated by Django 4.2.16 on 2025-01-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_transferitems_defect_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferitems',
            name='done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
