# Generated by Django 4.2.16 on 2024-11-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_supplieraccountspayments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='suppliers',
        ),
    ]
