# Generated by Django 5.2.1 on 2025-06-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_stocktakeitem_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktakeitem",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
