# Generated by Django 4.2.16 on 2025-01-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_transferitems_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
