# Generated by Django 4.2.16 on 2024-11-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_holdtransfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="hold",
            field=models.BooleanField(default=True),
        ),
    ]
