# Generated by Django 4.2.16 on 2024-11-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_transfer_hold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="hold",
            field=models.BooleanField(default=False),
        ),
    ]
