# Generated by Django 4.2.16 on 2025-01-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_accessory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='quantity',
        ),
    ]
