# Generated by Django 5.2.1 on 2025-06-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_alter_stocktakeitem_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktakeitem",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="note",
            field=models.TextField(default="", null=True),
        ),
    ]
