# Generated by Django 4.2.16 on 2025-01-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_accessory_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="image",
            field=models.ImageField(
                blank=True,
                default="placeholder.png",
                null=True,
                upload_to="product_images/",
            ),
        ),
    ]
