# Generated by Django 4.2.16 on 2024-11-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_product_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieraccount',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
