# Generated by Django 5.2.1 on 2025-06-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_alter_stocktakeitem_cost_alter_stocktakeitem_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktakeitem",
            name="company_loss",
            field=models.BooleanField(null=True),
        ),
    ]
