# Generated by Django 4.2.16 on 2024-11-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_alter_transfer_hold"),
    ]

    operations = [
        migrations.AddField(
            model_name="holdtransfer",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
