# Generated by Django 4.2.16 on 2024-11-27 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_alter_purchaseorderitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="product",
        ),
    ]
