# Generated by Django 4.2.16 on 2024-11-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_supplieraccount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieraccount',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
