# Generated by Django 4.2.16 on 2024-11-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_remove_purchaseorderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.inventory",
            ),
        ),
    ]
