# Generated by Django 4.2.16 on 2024-11-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_holdtransfer_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="holdtransfer",
            name="dealer_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="holdtransfer",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
