# Generated by Django 4.2.16 on 2024-11-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_supplieraccount_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplieraccount',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='supplieraccount',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
