# Generated by Django 5.2.1 on 2025-06-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_stocktakeitem_company_loss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktakeitem",
            name="company_loss",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
