# Generated by Django 5.2.1 on 2025-06-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0020_alter_stocktakeitem_company_loss"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktake",
            name="negative",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="negative_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="positive",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="positive_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
