# Generated by Django 4.2.16 on 2024-11-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_purchaseorderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=102),
        ),
        migrations.AlterField(
            model_name='supplieraccount',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='supplieraccountspayments',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplieraccount'),
        ),
        migrations.AlterField(
            model_name='supplieraccountspayments',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('bank', 'bank'), ('Ecocash', 'ecocash')], max_length=15),
        ),
    ]
