# Generated by Django 4.2.16 on 2024-11-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('inventory', '0020_alter_supplieraccount_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplieraccount',
            unique_together={('currency', 'supplier')},
        ),
    ]
