# Generated by Django 4.2.16 on 2024-11-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_supplieraccount_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
