# Generated by Django 5.2.1 on 2025-06-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0021_stocktake_negative_stocktake_negative_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktakeitem",
            name="recorded",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
