# Generated by Django 4.2.16 on 2024-12-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_supplier_contact_person_alter_supplier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
