# Generated by Django 4.2.16 on 2024-12-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_inventory_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='delete',
            new_name='disable',
        ),
    ]
