# Generated by Django 5.2.1 on 2025-06-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0022_stocktakeitem_recorded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktakeitem",
            name="accepted",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
    ]
