# Generated by Django 4.2.16 on 2025-06-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0023_alter_stocktakeitem_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktakeitem",
            name="now_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
