# Generated by Django 4.2.16 on 2024-12-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_rename_delete_inventory_disable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='disable',
        ),
    ]
