# Generated by Django 5.2.1 on 2025-06-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0025_inventorynotificationsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktakeitem",
            name="has_diff",
            field=models.BooleanField(default=False),
        ),
    ]
