# Generated by Django 4.2.16 on 2024-12-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_inventory_disable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='disable',
        ),
    ]
