# Generated by Django 5.2.1 on 2025-07-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_branch_disable"),
        ("inventory", "0026_stocktakeitem_has_diff"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["branch", "status", "disable"],
                name="inventory_i_branch__66a381_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["name"], name="inventory_i_name_43f130_idx"),
        ),
    ]
