# Generated by Django 4.2.16 on 2024-12-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_purchaseorderitem_cost_purchaseorderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
