# Generated by Django 4.2.16 on 2024-12-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_purchaseorderitem_wholesale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='cost',
        ),
    ]
