# Generated by Django 5.2.1 on 2025-07-10 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0028_alter_activitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="stocktake",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.stocktake",
            ),
        ),
    ]
