# Generated by Django 5.2.1 on 2025-09-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0029_activitylog_stocktake"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="stocktake",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.stocktake",
            ),
        ),
    ]
