# Generated by Django 4.2.16 on 2024-12-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_purchaseorderitem_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
