# Generated by Django 5.2.1 on 2025-09-22 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0030_alter_activitylog_stocktake"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktakeitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 9, 22, 10, 34, 36, 311617, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="still_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
