# Generated by Django 4.2.16 on 2024-12-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_inventory_disabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='disabled',
            new_name='disable',
        ),
    ]
