# Generated by Django 5.2.1 on 2025-09-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0031_stocktakeitem_created_at_stocktakeitem_still_open_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktakeitem",
            name="received_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="sold_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="transfer_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
