# Generated by Django 4.2.16 on 2024-12-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_rename_disabled_inventory_disable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='batch',
            field=models.TextField(blank=True, default=''),
        ),
    ]
