# Generated by Django 5.2.1 on 2025-09-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0032_stocktakeitem_received_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktakeitem",
            name="received_quantity",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="sold_quantity",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="transfer_quantity",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
