# Generated by Django 4.2.16 on 2024-12-14 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_inventory_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'supplier')},
        ),
    ]
