# Generated by Django 4.2.16 on 2024-12-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_productcategory_supplier_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='supplier',
        ),
    ]
