# Generated by Django 5.2.1 on 2025-09-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0033_alter_stocktakeitem_received_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktakeitem",
            name="quantity_difference",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
