# Generated by Django 4.2.16 on 2024-12-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_productcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='disable',
        ),
    ]
