# Generated by Django 4.2.16 on 2024-12-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_productcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktake',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='quantity',
        ),
        migrations.AddField(
            model_name='stocktake',
            name='result',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktake',
            name='s_t_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StocktakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('quantity_difference', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('stocktake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stocktake')),
            ],
        ),
    ]
