# Generated by Django 4.2.16 on 2024-12-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0035_remove_stocktake_product_remove_stocktake_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktake',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='result',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
