# Generated by Django 4.2.16 on 2024-12-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_remove_inventory_disable'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
