# Generated by Django 4.2.16 on 2024-12-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_stocktake_branch_stocktake_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('stock in', 'stock in'), ('Stock update', 'Stock update'), ('stock adjustment', 'stock adjustment'), ('update', 'Update'), ('delete', 'Delete'), ('edit', 'Edit'), ('transfer in', 'transfer in'), ('transfer out', 'transfer out'), ('returns', 'returns'), ('sale return', 'sale return'), ('sale', 'Sale'), ('declined', 'Declined'), ('write off', 'write off'), ('defective', 'defective'), ('activated', 'activated'), ('deactivated', 'deactivated'), ('removed', 'removed'), ('purchase edit +', 'purchase edit +'), ('purchase edit -', 'purchase edit -'), ('transfer cancel', 'transfer cancel')], max_length=20),
        ),
    ]
