# Generated by Django 4.2.16 on 2024-12-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_inventory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='tax_type',
        ),
    ]
