# Generated by Django 4.2.16 on 2024-10-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0038_alter_activitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferitems",
            name="receieved_quanity",
            field=models.IntegerField(default=96),
            preserve_default=False,
        ),
    ]
