# Generated by Django 4.2.16 on 2024-12-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_remove_inventory_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='tax_type',
            field=models.CharField(choices=[('exempted', 'Exempted'), ('standard', 'Standard'), ('zero rated', 'Zero Rated')], max_length=50, null=True),
        ),
    ]
