# Generated by Django 4.2.16 on 2024-12-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_inventory_tax_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
    ]
