# Generated by Django 4.2.16 on 2024-12-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_remove_inventory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
    ]
