# Generated by Django 4.2.16 on 2024-12-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_inventory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='price',
        ),
    ]
