# Generated by Django 4.2.16 on 2024-11-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0042_transfer_receive_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplier",
            old_name="contact_name",
            new_name="contact_person",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="address",
        ),
        migrations.AddField(
            model_name="supplier",
            name="products",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(max_length=255),
        ),
    ]
