# Generated by Django 4.2.16 on 2024-12-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_remove_purchaseorderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
            preserve_default=False,
        ),
    ]
