# Generated by Django 4.2.16 on 2024-12-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_purchaseorderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='price',
        ),
    ]
