# Generated by Django 4.2.16 on 2024-12-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_remove_purchaseorderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='wholesale_price',
        ),
    ]
