# Generated by Django 4.2.16 on 2025-01-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
