# Generated by Django 4.2.16 on 2025-01-07 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('printer_type', models.CharField(choices=[('bluetooth', 'Bluetooth'), ('system', 'System')], max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('pc_identifier', models.CharField(max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('system_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_creation', models.BooleanField(default=True)),
                ('product_update', models.BooleanField(default=True)),
                ('product_deletion', models.BooleanField(default=True)),
                ('invoice_on_sale', models.BooleanField(default=True)),
                ('low_stock', models.BooleanField(default=False)),
                ('service_creation', models.BooleanField(default=True)),
                ('service_update', models.BooleanField(default=True)),
                ('service_deletion', models.BooleanField(default=True)),
                ('transfer_creation', models.BooleanField(default=True)),
                ('transfer_approval', models.BooleanField(default=True)),
                ('transfer_receiving', models.BooleanField(default=True)),
                ('expense_creation', models.BooleanField(default=True)),
                ('expense_approval', models.BooleanField(default=True)),
                ('recurring_invoices', models.BooleanField(default=True)),
                ('money_transfer', models.BooleanField(default=True)),
                ('cash_withdrawal', models.BooleanField(default=True)),
                ('cash_deposits', models.BooleanField(default=True)),
                ('user_creation', models.BooleanField(default=True)),
                ('user_approval', models.BooleanField(default=True)),
                ('user_deletion', models.BooleanField(default=True)),
                ('user_login', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
