# Generated by Django 4.2.16 on 2025-01-22 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OfflineReceipt",
        ),
    ]
