# Generated by Django 4.2.16 on 2025-08-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_contact_creditnote_invoicecategory_valueaddedtax_and_more"),
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_no", models.IntegerField(default=1)),
                ("is_open", models.BooleanField(default=False)),
                ("global_count", models.IntegerField(default=0)),
                ("receipt_count", models.IntegerField(default=0)),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="offlinereceipt",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.invoice",
            ),
        ),
        migrations.CreateModel(
            name="FiscalCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fiscal_counter_type",
                    models.CharField(
                        choices=[
                            ("SaleByTax", "SaleByTax"),
                            ("SaleByVAT", "SaleByVAT"),
                            ("SaleTaxByTax", "SaleTaxByTax"),
                            ("Balancebymoneytype", "Balancebymoneytype"),
                            ("Other", "Other"),
                        ],
                        default="SaleByTax",
                        max_length=30,
                    ),
                ),
                (
                    "fiscal_counter_currency",
                    models.CharField(
                        choices=[("USD", "usd"), ("ZWG", "zwg")],
                        default="USD",
                        max_length=10,
                    ),
                ),
                (
                    "fiscal_counter_tax_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("fiscal_counter_tax_id", models.IntegerField(default=3)),
                (
                    "fiscal_counter_money_type",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Card", "Card"),
                            ("BankTransfer", "Bank Transfer"),
                            ("MobileMoney", "Mobile Money"),
                        ],
                        default="Cash",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "fiscal_counter_value",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fiscal_day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counters",
                        to="settings.fiscalday",
                    ),
                ),
            ],
        ),
    ]
