# Generated by Django 4.2.16 on 2025-01-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_delete_offlinereceipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted", models.BooleanField(default=False)),
            ],
        ),
    ]
