# Generated by Django 4.2.16 on 2025-08-29 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_fiscalday_offlinereceipt_invoice_fiscalcounter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fiscalcounter",
            name="fiscal_day",
        ),
    ]
