# Generated by Django 4.2.16 on 2025-08-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_remove_fiscalcounter_fiscal_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalcounter",
            name="fiscal_day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counters",
                to="settings.fiscalday",
            ),
        ),
    ]
