# Generated by Django 4.2.16 on 2025-08-29 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_fiscalcounter_fiscal_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offlinereceipt",
            name="invoice",
        ),
    ]
