# Generated by Django 4.2.16 on 2025-03-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_fiscalday"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalday",
            name="receipt_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fiscalday",
            name="total_sales",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
