# Generated by Django 4.2.16 on 2025-03-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0005_fiscalday_receipt_count_fiscalday_total_sales"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fiscal_counter_type",
                    models.CharField(
                        choices=[
                            ("SaleByTax", "Sale By Tax"),
                            ("SaleByVAT", "Sale By VAT"),
                            ("Other", "Other"),
                        ],
                        default="SaleByTax",
                        max_length=20,
                    ),
                ),
                (
                    "fiscal_counter_currency",
                    models.CharField(default="USD", max_length=10),
                ),
                (
                    "fiscal_counter_tax_percent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("fiscal_counter_tax_id", models.IntegerField(default=0)),
                (
                    "fiscal_counter_money_type",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Card", "Card"),
                            ("BankTransfer", "Bank Transfer"),
                            ("MobileMoney", "Mobile Money"),
                        ],
                        default="Cash",
                        max_length=20,
                    ),
                ),
                ("fiscal_counter_value", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
