# Generated by Django 4.2.16 on 2025-08-29 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0015_invoiceitem_credit_note_amount_and_more"),
        ("settings", "0005_remove_offlinereceipt_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="offlinereceipt",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.invoice",
            ),
        ),
    ]
