# Generated by Django 4.2.16 on 2025-03-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0006_fiscalcounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalday",
            name="global_count",
            field=models.IntegerField(default=0),
        ),
    ]
