# Generated by Django 4.2.16 on 2025-11-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0006_offlinereceipt_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalday",
            name="lastReceiptGlobalCount",
            field=models.IntegerField(default=0),
        ),
    ]
