# Generated by Django 4.2.16 on 2025-03-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0007_fiscalday_global_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalcounter",
            name="fiscal_counter_tax_id",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="fiscalcounter",
            name="fiscal_counter_value",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
