# Generated by Django 4.2.16 on 2025-11-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0007_fiscalday_lastreceiptglobalcount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalday",
            name="lastReceiptGlobalCount",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
