# Generated by Django 4.2.16 on 2025-04-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0008_alter_fiscalcounter_fiscal_counter_tax_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalcounter",
            name="fiscal_counter_type",
            field=models.CharField(
                choices=[
                    ("SaleByTax", "Sale By Tax"),
                    ("SaleByVAT", "Sale By VAT"),
                    ("Sale Tax By Tax", "Sale Tax By Tax"),
                    ("Balance by money type", "Balance by money type"),
                    ("Other", "Other"),
                ],
                default="SaleByTax",
                max_length=30,
            ),
        ),
    ]
