# Generated by Django 4.2.16 on 2025-04-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0009_alter_fiscalcounter_fiscal_counter_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalcounter",
            name="fiscal_counter_money_type",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Card", "Card"),
                    ("BankTransfer", "Bank Transfer"),
                    ("MobileMoney", "Mobile Money"),
                ],
                default="Cash",
                max_length=20,
                null=True,
            ),
        ),
    ]
