# Generated by Django 4.2.16 on 2025-11-27 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0009_whatsappconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fiscalday",
            name="lastReceiptGlobalCount",
        ),
        migrations.DeleteModel(
            name="WhatsAppConfig",
        ),
    ]
