# Generated by Django 4.2.16 on 2025-11-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0010_remove_fiscalday_lastreceiptglobalcount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalday",
            name="lastReceiptGlobalCount",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
