# Generated by Django 4.2.16 on 2025-04-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0010_alter_fiscalcounter_fiscal_counter_money_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalcounter",
            name="fiscal_counter_type",
            field=models.CharField(
                choices=[
                    ("SaleByTax", "Sale By Tax"),
                    ("SaleByVAT", "Sale By VAT"),
                    ("SaleTaxByTax", "Sale Tax By Tax"),
                    ("Balancebymoneytype", "Balance by money type"),
                    ("Other", "Other"),
                ],
                default="SaleByTax",
                max_length=30,
            ),
        ),
    ]
