# Generated by Django 4.2.16 on 2025-04-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0011_alter_fiscalcounter_fiscal_counter_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalcounter",
            name="fiscal_counter_currency",
            field=models.CharField(
                choices=[("USD", "usd"), ("ZWG", "zwg")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="fiscalcounter",
            name="fiscal_counter_type",
            field=models.CharField(
                choices=[
                    ("SaleByTax", "SaleByTax"),
                    ("SaleByVAT", "SaleByVAT"),
                    ("SaleTaxByTax", "SaleTaxByTax"),
                    ("Balancebymoneytype", "Balancebymoneytype"),
                    ("Other", "Other"),
                ],
                default="SaleByTax",
                max_length=30,
            ),
        ),
    ]
