# Generated by Django 4.2.16 on 2025-11-27 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0012_remove_fiscalday_lastreceiptglobalcount_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WhatsAppConfig",
        ),
    ]
