# Generated by Django 5.2.1 on 2025-09-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0014_alter_fiscalcounter_fiscal_counter_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="dbBackUps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="backups/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
