# Generated by Django 4.2.16 on 2025-05-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0022_invoice_cash_up_status"),
        ("settings", "0014_alter_fiscalcounter_fiscal_counter_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="offlinereceipt",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.invoice",
            ),
        ),
    ]
