# Generated by Django 4.2.16 on 2025-08-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0015_offlinereceipt_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalcounter",
            name="fiscal_counter_tax_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5, null=True
            ),
        ),
    ]
