# Generated by Django 4.2.16 on 2024-11-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("measurement", models.CharField(max_length=255)),
                ("recorded", models.DecimalField(decimal_places=4, max_digits=10)),
                ("date", models.DateField()),
                (
                    "Types",
                    models.ForeignKey(
                        max_length=255,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.types",
                    ),
                ),
            ],
        ),
    ]
