# Generated by Django 4.2.16 on 2024-12-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
    ]
