# Generated by Django 4.2.16 on 2024-12-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itemofuse',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itemofuse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='itemofuse',
            name='service',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='Members',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='Payments',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='Services',
        ),
        migrations.RemoveField(
            model_name='memberaccounts',
            name='Payments',
        ),
        migrations.RemoveField(
            model_name='members',
            name='Member_accounts',
        ),
        migrations.RemoveField(
            model_name='members',
            name='Payments',
        ),
        migrations.RemoveField(
            model_name='members',
            name='Services',
        ),
        migrations.DeleteModel(
            name='ServiceRange',
        ),
        migrations.RemoveField(
            model_name='services',
            name='unit_measure',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='inventory',
        ),
        migrations.DeleteModel(
            name='ItemOfUse',
        ),
        migrations.DeleteModel(
            name='itemOfUseName',
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.DeleteModel(
            name='MemberAccounts',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='UnitMeasurement',
        ),
    ]
