# Generated by Django 4.2.16 on 2024-12-04 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemofuse',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemofuse',
            name='service_range',
        ),
        migrations.RemoveField(
            model_name='itemofuse',
            name='unit_measure',
        ),
        migrations.AddField(
            model_name='services',
            name='service_range',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='services',
            name='unit_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.unitmeasurement'),
        ),
    ]
