# Generated by Django 4.2.16 on 2024-12-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemofuse',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itemofuse',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='itemofuse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itemofuse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='itemofuse',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='itemofuse',
            name='service',
        ),
    ]
