# Generated by Django 4.2.16 on 2024-11-08 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Office_spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default=django.utils.timezone.now)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RenameField(
            model_name='services',
            old_name='measurement',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='types',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='services',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='services',
            name='date',
        ),
        migrations.RemoveField(
            model_name='services',
            name='name',
        ),
        migrations.RemoveField(
            model_name='services',
            name='price',
        ),
        migrations.RemoveField(
            model_name='services',
            name='recorded',
        ),
        migrations.AddField(
            model_name='types',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='types',
            name='Promotion',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='types',
            name='Service_duration',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('National_ID', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=255)),
                ('Phone', models.CharField(max_length=12)),
                ('Address', models.CharField(max_length=255)),
                ('Company', models.CharField(blank=True, max_length=255)),
                ('Age', models.IntegerField()),
                ('Member_accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.member_accounts')),
                ('Office_spaces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.office_spaces')),
                ('Payments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.payments')),
                ('Services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.services')),
            ],
        ),
        migrations.AddField(
            model_name='member_accounts',
            name='Payments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.payments'),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'create'), ('delete', 'delete'), ('update', 'update'), ('read', 'read')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.members')),
                ('Payments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.payments')),
                ('Services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_file', to='booking.services')),
            ],
        ),
    ]
