# Generated by Django 4.2.16 on 2024-12-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemofuse',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
