# Generated by Django 4.2.16 on 2024-12-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_services_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='Members',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='Payments',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='Services',
        ),
        migrations.RemoveField(
            model_name='members',
            name='Services',
        ),
        migrations.DeleteModel(
            name='ItemOfUse',
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
