# Generated by Django 4.2.16 on 2024-12-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_itemofuse_category_remove_itemofuse_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemofuse',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemofuse',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='itemofuse',
            name='description',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='itemofuse',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.itemofusename'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemofuse',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemofuse',
            name='service',
            field=models.ManyToManyField(to='booking.services'),
        ),
    ]
