# Generated by Django 4.2.16 on 2024-11-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_member_accounts_office_spaces_payments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='Service_duration',
        ),
        migrations.AddField(
            model_name='member_accounts',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='members',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='Admin_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='services',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='types',
            name='Duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='logs',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('update', 'update'), ('read', 'read'), ('delete', 'delete')], max_length=10),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='member_accounts',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='members',
            name='Member_accounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.member_accounts'),
        ),
        migrations.AlterField(
            model_name='members',
            name='Office_spaces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.office_spaces'),
        ),
        migrations.AlterField(
            model_name='members',
            name='Payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.payments'),
        ),
        migrations.AlterField(
            model_name='members',
            name='Services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.services'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='Amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
