# Generated by Django 4.2.16 on 2024-12-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_inventory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='casper', max_length=255),
            preserve_default=False,
        ),
    ]
