# Generated by Django 4.2.16 on 2024-12-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_itemofuse_delete_services_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemofuse',
            old_name='delete',
            new_name='delete_iou',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='delete',
            new_name='delete_s',
        ),
    ]
