# Generated by Django 4.2.16 on 2024-12-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_inventory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
    ]
