# Generated by Django 4.2.16 on 2024-11-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_types_service_duration_member_accounts_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='Description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
