# Generated by Django 4.2.16 on 2024-12-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_itemofuse_category_itemofuse_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemofuse',
            name='description',
            field=models.CharField(default='none', max_length=255, null=True),
        ),
    ]
