# Generated by Django 4.2.16 on 2024-12-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_delete_itemofuse_delete_iou_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='Member_accounts',
        ),
        migrations.RemoveField(
            model_name='members',
            name='Payments',
        ),
        migrations.RemoveField(
            model_name='members',
            name='Services',
        ),
        migrations.AddField(
            model_name='memberaccounts',
            name='Member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.members'),
        ),
        migrations.AddField(
            model_name='payments',
            name='Member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.members'),
        ),
    ]
