# Generated by Django 4.2.16 on 2024-12-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_logs_members_remove_logs_payments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('description', models.CharField(default='none', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('read', 'read'), ('delete', 'delete')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.members')),
                ('Payments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.payments')),
                ('Services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_file', to='booking.services')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('description', models.CharField(default='none', max_length=255)),
                ('service_range', models.CharField(default='none', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.category')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.itemofusename')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.services')),
                ('unit_measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.unitmeasurement')),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='Services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.services'),
        ),
    ]
