# Generated by Django 4.2.16 on 2024-12-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemofuse',
            name='service',
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='itemofuse',
            name='service',
            field=models.ManyToManyField(to='booking.services'),
        ),
    ]
