# Generated by Django 4.2.16 on 2024-12-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_itemofuse_description'),
        ('booking', '0004_remove_itemofuse_service_alter_services_service_name_and_more'),
    ]

    operations = [
    ]
