# Generated by Django 4.2.16 on 2024-12-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_inventory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='casy', max_length=255),
            preserve_default=False,
        ),
    ]
