# Generated by Django 4.2.16 on 2024-12-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_members_member_accounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberaccounts',
            name='Payments',
        ),
        migrations.AddField(
            model_name='members',
            name='Enrollmnet',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='Gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='Account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.memberaccounts'),
        ),
    ]
