# Generated by Django 4.2.16 on 2024-12-03 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_services_logs_itemofuse_members_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemofuse',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.itemofuse'),
            preserve_default=False,
        ),
    ]
