# Generated by Django 4.2.16 on 2024-11-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_payments_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service_product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('service_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service_product')),
            ],
        ),
        migrations.CreateModel(
            name='Service_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_range', models.CharField(default='None', max_length=40)),
                ('service_product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service_product_details')),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=60)),
                ('promotion', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='services',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Types',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
        migrations.AddField(
            model_name='service_product',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.services'),
        ),
    ]
