# Generated by Django 4.2.16 on 2024-12-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_products_inventory_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(default='casy', on_delete=django.db.models.deletion.CASCADE, to='booking.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
