# Generated by Django 4.2.16 on 2024-11-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_service_product_service_product_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_range',
            name='service_product_details',
        ),
        migrations.RemoveField(
            model_name='unit_measurement',
            name='promotion',
        ),
        migrations.AddField(
            model_name='service_range',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service_range',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service_range',
            name='service_product',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='booking.service_product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit_measurement',
            name='service_product',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='booking.service_product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service_product_details',
        ),
    ]
