# Generated by Django 4.2.16 on 2024-12-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_memberaccounts_payments_members_enrollmnet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Enrollmnet',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
