# Generated by Django 4.2.16 on 2024-11-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_service_range_service_product_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_range',
            name='promotion',
        ),
        migrations.AddField(
            model_name='unit_measurement',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
