# Generated by Django 4.2.16 on 2024-12-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_members_enrollmnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(default='none', max_length=255, null=True),
        ),
    ]
