# Generated by Django 4.2.16 on 2024-12-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_delete_products_inventory_category_inventory_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemOfUseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_of_use_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='itemofuse',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.itemofusename'),
        ),
    ]
