# Generated by Django 4.2.16 on 2024-12-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_services_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='customer_type',
            field=models.CharField(choices=[('patients', 'patients')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
