# Generated by Django 4.2.16 on 2024-11-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_service_range_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_range',
            name='price',
        ),
    ]
