# Generated by Django 4.2.16 on 2024-12-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_services_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemofuse',
            name='delete_iou',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
