# Generated by Django 4.2.16 on 2024-11-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_service_range_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_range',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
