# Generated by Django 4.2.16 on 2024-11-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_service_range_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_range',
            name='service_product',
        ),
    ]
