# Generated by Django 4.2.16 on 2024-11-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_service_range_service_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_range',
            name='service_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service_product'),
        ),
    ]
