# Generated by Django 4.2.16 on 2024-11-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_service_range_service_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_range',
            name='service_product',
        ),
    ]
