# Generated by Django 4.2.16 on 2024-11-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_service_range_service_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit_measurement',
            name='service_product',
        ),
    ]
