# Generated by Django 4.2.16 on 2024-11-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_remove_unit_measurement_service_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_measurement',
            name='service_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.service_product'),
            preserve_default=False,
        ),
    ]
