# Generated by Django 4.2.16 on 2024-11-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_unit_measurement_service_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_range',
        ),
    ]
