# Generated by Django 4.2.16 on 2024-11-28 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_delete_service_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_range', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service_product')),
            ],
        ),
    ]
