# Generated by Django 4.2.16 on 2024-11-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_remove_service_range_service_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_product',
            name='service_range',
        ),
        migrations.RemoveField(
            model_name='service_product',
            name='unit_measure',
        ),
    ]
