# Generated by Django 4.2.16 on 2024-11-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_service_product_service_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_product',
            name='service_range',
        ),
        migrations.RemoveField(
            model_name='service_product',
            name='unit_measure',
        ),
        migrations.AddField(
            model_name='service_range',
            name='service_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.service_product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit_measurement',
            name='service_product',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='booking.service_product'),
            preserve_default=False,
        ),
    ]
