# Generated by Django 4.2.16 on 2024-11-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_remove_service_product_service_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_range',
            name='service_product',
        ),
        migrations.RemoveField(
            model_name='unit_measurement',
            name='service_product',
        ),
        migrations.AddField(
            model_name='service_product',
            name='service_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.service_range'),
        ),
        migrations.AddField(
            model_name='service_product',
            name='unit_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.unit_measurement'),
        ),
    ]
