# Generated by Django 4.2.16 on 2024-11-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_remove_service_range_service_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_range',
            name='service_range',
        ),
    ]
