# Generated by Django 4.2.16 on 2024-11-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_remove_service_range_service_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_range',
            name='service_range',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
