# Generated by Django 4.2.16 on 2024-11-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_service_range_service_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_product',
            name='service_range',
        ),
    ]
