# Generated by Django 4.2.16 on 2024-11-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_remove_service_product_service_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_product',
            name='service_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.service_range'),
        ),
    ]
