# Generated by Django 4.2.16 on 2024-11-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_service_product_service_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_product',
            name='unit_measure',
        ),
    ]
