# Generated by Django 4.2.16 on 2024-11-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_remove_service_product_unit_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_product',
            name='unit_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.unit_measurement'),
        ),
    ]
