# Generated by Django 4.2.16 on 2024-11-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_service_product_unit_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit_measurement',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='unit_measurement',
            name='promotion',
        ),
    ]
