# Generated by Django 4.2.16 on 2024-11-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_remove_unit_measurement_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_measurement',
            name='measurement',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit_measurement',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
