# Generated by Django 4.2.16 on 2024-11-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_unit_measurement_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_measurement',
            name='measurement',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
