# Generated by Django 4.2.16 on 2024-12-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_alter_unit_measurement_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
