# Generated by Django 4.2.16 on 2024-12-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_services_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_product',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.services'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service_product',
            name='service_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service_range'),
        ),
        migrations.AlterField(
            model_name='service_product',
            name='unit_measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.unit_measurement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit_measurement',
            name='measurement',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
