# Generated by Django 4.2.16 on 2024-12-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_alter_service_product_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.services')),
            ],
        ),
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=60, null=True)),
                ('promotion', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Member_accounts',
            new_name='MemberAccounts',
        ),
        migrations.RemoveField(
            model_name='service_product',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_product',
            name='service_range',
        ),
        migrations.RemoveField(
            model_name='service_product',
            name='unit_measure',
        ),
        migrations.RemoveField(
            model_name='members',
            name='Office_spaces',
        ),
        migrations.RenameModel(
            old_name='Service_range',
            new_name='ServiceRange',
        ),
        migrations.DeleteModel(
            name='Office_spaces',
        ),
        migrations.DeleteModel(
            name='Service_product',
        ),
        migrations.DeleteModel(
            name='Unit_Measurement',
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='service_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.servicerange'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='unit_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.unitmeasurement'),
        ),
    ]
