# Generated by Django 4.2.16 on 2024-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_serviceproduct_unitmeasurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitmeasurement',
            name='promotion',
        ),
        migrations.AddField(
            model_name='servicerange',
            name='service_from',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='servicerange',
            name='service_to',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
