# Generated by Django 4.2.16 on 2024-12-02 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0039_remove_unitmeasurement_promotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('description', models.CharField(default='none', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicerange',
            name='service_from',
        ),
        migrations.RemoveField(
            model_name='servicerange',
            name='service_to',
        ),
        migrations.RemoveField(
            model_name='services',
            name='delete',
        ),
        migrations.AlterField(
            model_name='servicerange',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='servicerange',
            name='service_range',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.DeleteModel(
            name='ServiceProduct',
        ),
        migrations.AddField(
            model_name='itemofuse',
            name='service_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.servicerange'),
        ),
        migrations.AddField(
            model_name='itemofuse',
            name='unit_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='services',
            name='itemofuse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.itemofuse'),
        ),
    ]
