# Generated by Django 4.2.16 on 2024-12-03 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_category_itemofuse_remove_servicerange_service_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='itemofuse',
        ),
        migrations.AddField(
            model_name='itemofuse',
            name='quantity',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='itemofuse',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.services'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemofuse',
            name='service_range',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
